### ISSUE TITLE
Parse buildinfo file

### ISSUE THREAD

**Issue by SantiagoTorres** [TSELab/guac-alytics#1]
Create a script under `scripts/ingestion` to handle the debian project's `.buildinfo` file format  (spec [here](https://wiki.debian.org/ReproducibleBuilds/BuildinfoFiles)).

The output format should at a minimum follow the following schema:

` source | package | architecture | version | dependencies (as a list of packages) `

- [x] Parse .buildinfo file
- [x] Test correctness against package repositories
- [x] Handle split package case
   - Identify split packages
   - Create one entry for each split package

**Comment by SantiagoTorres** [comment]
Provide a function/script under `scripts/ingestion` to collect and parse the buildinfo files provided by the debian project

The schema of the files should follow:

 `source | package name | version | architecture | timestamp | list of dependencies  (as package names)`
 
 - [ ] Prepare script to ingest
 - [ ] Test distinction between source and package
 - [ ] Handle the split package case:
   - Identify split package case
   - Create two entries per split package

**Comment by sbrunswi** [comment]
@SahithiKasim  - I think Santiago had asked you to make a pull request

**Comment by SahithiKasim** [comment]
I made the pull request.

**Comment by SantiagoTorres** [comment]
we close the issues when the PR is merged, not when it's open
