### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by SahithiKasim** [TSELab/guac-alytics#11]
Create ER diagram of the database schema and do the documentation for the whole database.

**Comment by SahithiKasim** [comment]
### Please check this ER diagram @SantiagoTorres @sbrunswi and tell me the required changes.

![ER diagram](https://user-images.githubusercontent.com/71808684/217883100-d685c863-5375-4c29-84cc-fb212a07a1f0.png)

**Comment by SantiagoTorres** [comment]
I think we should split/explode buildinfo_data into different tables:

1. Package table:
    - PackageID (PK)
    - BuildinfoID (i.e., created by)
    - Arch (from buildinfo)
    - Name (from buildinfo)
    - Version (from buildinfo)
    - Type (source/binary)
 2. Source table:
     - SourceID (PK)
     - Name (from Buildinfo, later to cross-check)
     - Version (from buildinfo, later to cross-check)
     - location (where is the source coming from, TBD)
 3. buildinfoTable:
     - BuildinfoID (PK)
     - SourceID (EK, what source was used)
     - deps (list of PackageIDs)
     
 Does this make sense?

**Comment by SahithiKasim** [comment]
I didn't understand about **BuildinfoID** and **Type** from the Package table. Is **PackageID** an integer that automatically increments? \
What is **SourceID** in the Source table?\
 Are the **BuildinfoID** and **SourceID** in the buildinfo table foreign keys from other tables?

**Comment by SantiagoTorres** [comment]
Pretty much, the ones labeled as PK are primary keys on each table

**Comment by SahithiKasim** [comment]
### **The Updated ER diagram**

![ER diagram](https://user-images.githubusercontent.com/71808684/218607787-7de8f50a-be6b-46cc-a0fc-0239b8107d7d.png)

**Comment by SahithiKasim** [comment]
Updated in the readme
