### ISSUE TITLE
Handle popcon data

### ISSUE THREAD

**Issue by SantiagoTorres** [TSELab/guac-alytics#2]
We require to handle the popcon data dump. Similarly to #1, we want to handle this file type under a script/library under `scripts/ingestion`. The expected schema should follow the popcon tabular description:

`#rank name                            inst  vote   old recent no-files (maintainer)`

(see the rest of the format description):

```
#Format
#
#<name> is the package name;
#<inst> is the number of people who installed this package;
#<vote> is the number of people who use this package regularly;
#<old> is the number of people who installed, but don't use this package
#      regularly;
#<recent> is the number of people who upgraded this package recently;
#<no-files> is the number of people whose entry didn't contain enough
#           information (atime and ctime were 0).
```

**Comment by SahithiKasim** [comment]
I have built the popularity table (popcon) with this schema:

> _name inst vote old recent no-files maintainer inst_norm vote_norm_


You can find it - _**data/yellow/vineet/database/bi_multi_tables.db/popularity_table**_   in this table

**Comment by SantiagoTorres** [comment]
I would like to see the script, rather than the table

**Comment by sbrunswi** [comment]
@SantiagoTorres  - I think this is complete! what was the commit for this?

**Comment by SahithiKasim** [comment]
Check the updated code from #4!
