### ISSUE TITLE
Create a table on publish in supply chain

### ISSUE THREAD

**Issue by SahithiKasim** [TSELab/guac-alytics#23]
- Create a literature review table for the publish portion of the supply chain
- Create a parser to fetch publish data from snapshots and store into DB

**Comment by SahithiKasim** [comment]
Please check the drive for more information - https://drive.google.com/drive/folders/1Ea21f5vJiTSPFlk1ZRlN9q9ve8jGAyap?usp=sharing

**Comment by absol27** [comment]
- Created new tables on overleaf for useful resources related to upstream code and publish packages
- Pushed the code to query a snapshot using Architecture and Date, get a list of all packages and it's dependencies from the stable distro at the selected date.

Repo to code -- https://github.com/absol27/Debian_Dependency
