### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by SantiagoTorres** [TSELab/guac-alytics#3]
Regardless of the database type we will eventually use, we need to distinguish/define a series of concepts related to the data we are collecting. Here are some to get started

0. Software Artifact: a unit of exchange of software. This can be a package, a source code repository, a docker container, etc.
1. Maintainer: an individual/group/software-entity that acts on software artifacts
2. Package: a type of software artifact for distribution to end users
3. Source: a type of software artifact used by maintainers to create a package

I'm sure there are more, but I want to help disambiguate things ...

**Comment by sbrunswi** [comment]
I think we can close this as well @SantiagoTorres  @SahithiKasim
