### ISSUE TITLE
CERIAS Research Report

### ISSUE THREAD

**Issue by SahithiKasim** [TSELab/guac-alytics#33]
Please revise the abstract available at [this link](https://www.cerias.purdue.edu/webapps/index.php/research_report/main/index/DZq8Cw84) and send the updated version to [researchreport@cerias.purdue.edu](mailto:researchreport@cerias.purdue.edu) regarding the "Developing New Mechanisms to Enable Open Source Software (OSS) Supply Chain Transparency" project by 5:00 PM ET on Thursday, September 14th.

**Comment by SahithiKasim** [comment]
Professor @SantiagoTorres could you kindly make the update by tomorrow, as that's the deadline?

**Comment by SantiagoTorres** [comment]
Done
